owner: KevvTheGoat # Your GitHub organization or username, where this repository lives
repo: ks-status # The name of this repository

sites:
  - name: Kevin Service Main Site
    url: https://www.kevsrv.me
  - name: Kevin Service Registry
    url: https://registry.kevsrv.me
    icon: https://www.kevsrv.me/assets/images/favicon.ico
  - name: Kevin Service Registry Backend
    url: https://registry.kevsrv.me/api/
    icon: https://www.kevsrv.me/assets/images/favicon.ico
    expectedStatusCodes:
      - 404
  - name: Kevin Service Free Hosting
    url: https://free.kevsrv.me
  - name: Kevin Service Free Hosting Backend
    icon: https://www.kevsrv.me/assets/images/favicon.ico
    url: https://free.kevsrv.me/api/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kevsrv.me
  # baseUrl: /your-repo-name
  logoUrl: https://www.kevsrv.me/assets/images/logo.png
  name: Status
  introTitle: "Kevin Service Status"
  introMessage: This is a status page for all services under Kevin Service
  navbar:
    - title: Home
      href: https://kevsrv.me
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
